version: 0.2

# =============================================================================
# CodeBuild 빌드 명세서 (ECS/ECR 버전)
# =============================================================================
# Docker 이미지 빌드 후 ECR에 푸시
# =============================================================================

env:
  variables:
    AWS_REGION: ap-northeast-2
    ECR_REPO_NAME: plcr-ecr-app-repo  # ECR 리포지토리 이름으로 변경

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Image tag = $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG -f apps/app/Dockerfile .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo "Creating imagedefinitions.json for ECS..."
      - printf '[{"name":"plcr-container-app","imageUri":"%s"}]' $ECR_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json